### ISSUE TITLE
The game not open

### ISSUE THREAD

**Issue by zHeuzy** [Offline-Cheatbreaker/Client#2]
**Describe the bug**

R: My game downloads everything normal but when starting it is "starting" infinitely

**To Reproduce**
1. Go to Home
2. Click on 1.7.10 or 1.8.9
3. And Wait

**Expected behavior**

R: I expected the game to open but that was not the case

**Screenshots**
[Screenshot_1](https://user-images.githubusercontent.com/78114033/106057273-8244ab80-60ce-11eb-9cd9-fa1716e436c8.png)

**Please complete the following information:**
 - OS:  Windows 10
 - Game version: 1.8.9 and 1.7.10
 - Game build number [e.g. `03d0882`]
 - Launcher version Beta 6

 - If on **Linux**, provide the output of `java -version` from Terminal

**Additional context**

**Comment by ShonP40** [comment]
Can you check if there are any errors in the `log.log` file from `%appdata%\Offline CheatBreaker`?

**Comment by zHeuzy** [comment]
2021-01-27 18:11:46.566] [info] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.llIIIlIlIllllIIllllIIIIll(Minecraft:578) [Offline%20CheatBreaker%201.8.9.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.IIlIIIIlllIlIIllIIIIlIlll(Minecraft:444) [Offline%20CheatBreaker%201.8.9.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.lIIIIllIllIIIIlIIlllIIlII(Minecraft:362) [Offline%20CheatBreaker%201.8.9.jar:?]
	at lIIIllllllIIIllllIlIIlllI.lIIIlIlIIllllIllIIllIllIl(Minecraft:113) [Offline%20CheatBreaker%201.8.9.jar:?]
	at Start.main(Minecraft:13) [Offline%20CheatBreaker%201.8.9.jar:?]

[2021-01-27 18:11:46.567] [info] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.llIIIlIlIllllIIllllIIIIll(Minecraft:578) [Offline%20CheatBreaker%201.8.9.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.IIlIIIIlllIlIIllIIIIlIlll(Minecraft:444) [Offline%20CheatBreaker%201.8.9.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.lIIIIllIllIIIIlIIlllIIlII(Minecraft:362) [Offline%20CheatBreaker%201.8.9.jar:?]
	at lIIIllllllIIIllllIlIIlllI.lIIIlIlIIllllIllIIllIllIl(Minecraft:113) [Offline%20CheatBreaker%201.8.9.jar:?]
	at Start.main(Minecraft:13) [Offline%20CheatBreaker%201.8.9.jar:?]

[2021-01-27 18:11:46.570] [info] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.llIIIlIlIllllIIllllIIIIll(Minecraft:578) [Offline%20CheatBreaker%201.8.9.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.IIlIIIIlllIlIIllIIIIlIlll(Minecraft:444) [Offline%20CheatBreaker%201.8.9.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.lIIIIllIllIIIIlIIlllIIlII(Minecraft:362) [Offline%20CheatBreaker%201.8.9.jar:?]
	at lIIIllllllIIIllllIlIIlllI.lIIIlIlIIllllIllIIllIllIl(Minecraft:113) [Offline%20CheatBreaker%201.8.9.jar:?]
	at Start.main(Minecraft:13) [Offline%20CheatBreaker%201.8.9.jar:?]

[2021-01-27 18:11:46.571] [info] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.llIIIlIlIllllIIllllIIIIll(Minecraft:578) [Offline%20CheatBreaker%201.8.9.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.IIlIIIIlllIlIIllIIIIlIlll(Minecraft:444) [Offline%20CheatBreaker%201.8.9.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.lIIIIllIllIIIIlIIlllIIlII(Minecraft:362) [Offline%20CheatBreaker%201.8.9.jar:?]
	at lIIIllllllIIIllllIlIIlllI.lIIIlIlIIllllIllIIllIllIl(Minecraft:113) [Offline%20CheatBreaker%201.8.9.jar:?]
	at Start.main(Minecraft:13) [Offline%20CheatBreaker%201.8.9.jar:?]

[2021-01-27 18:11:46.572] [info] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.llIIIlIlIllllIIllllIIIIll(Minecraft:578) [Offline%20CheatBreaker%201.8.9.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.IIlIIIIlllIlIIllIIIIlIlll(Minecraft:444) [Offline%20CheatBreaker%201.8.9.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.lIIIIllIllIIIIlIIlllIIlII(Minecraft:362) [Offline%20CheatBreaker%201.8.9.jar:?]
	at lIIIllllllIIIllllIlIIlllI.lIIIlIlIIllllIllIIllIllIl(Minecraft:113) [Offline%20CheatBreaker%201.8.9.jar:?]
	at Start.main(Minecraft:13) [Offline%20CheatBreaker%201.8.9.jar:?]

[2021-01-27 18:11:46.573] [info] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.llIIIlIlIllllIIllllIIIIll(Minecraft:578) [Offline%20CheatBreaker%201.8.9.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.IIlIIIIlllIlIIllIIIIlIlll(Minecraft:444) [Offline%20CheatBreaker%201.8.9.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.lIIIIllIllIIIIlIIlllIIlII(Minecraft:362) [Offline%20CheatBreaker%201.8.9.jar:?]
	at lIIIllllllIIIllllIlIIlllI.lIIIlIlIIllllIllIIllIllIl(Minecraft:113) [Offline%20CheatBreaker%201.8.9.jar:?]
	at Start.main(Minecraft:13) [Offline%20CheatBreaker%201.8.9.jar:?]

[2021-01-27 18:11:46.573] [info] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.llIIIlIlIllllIIllllIIIIll(Minecraft:578) [Offline%20CheatBreaker%201.8.9.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.IIlIIIIlllIlIIllIIIIlIlll(Minecraft:444) [Offline%20CheatBreaker%201.8.9.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.lIIIIllIllIIIIlIIlllIIlII(Minecraft:362) [Offline%20CheatBreaker%201.8.9.jar:?]
	at lIIIllllllIIIllllIlIIlllI.lIIIlIlIIllllIllIIllIllIl(Minecraft:113) [Offline%20CheatBreaker%201.8.9.jar:?]
	at Start.main(Minecraft:13) [Offline%20CheatBreaker%201.8.9.jar:?]

[2021-01-27 18:11:46.574] [info] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.llIIIlIlIllllIIllllIIIIll(Minecraft:578) [Offline%20CheatBreaker%201.8.9.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.IIlIIIIlllIlIIllIIIIlIlll(Minecraft:444) [Offline%20CheatBreaker%201.8.9.jar:?]
	at llIlllIIllIIIlIlIlIllIIII.lIIIIllIllIIIIlIIlllIIlII(Minecraft:362) [Offline%20CheatBreaker%201.8.9.jar:?]
	at lIIIllllllIIIllllIlIIlllI.lIIIlIlIIllllIllIIllIllIl(Minecraft:113) [Offline%20CheatBreaker%201.8.9.jar:?]
	at Start.main(Minecraft:13) [Offline%20CheatBreaker%201.8.9.jar:?]

[2021-01-27 18:11:48.637] [info] ---- Minecraft Crash Report ----
1.8.9-?

// Who set us up the TNT?

Time: 1/27/21 7:11 PM
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at llIlllIIllIIIlIlIlIllIIII.llIIIlIlIllllIIllllIIIIll(Minecraft:598)
	at llIlllIIllIIIlIlIlIllIIII.IIlIIIIlllIlIIllIIIIlIlll(Minecraft:444)
	at llIlllIIllIIIlIlIlIllIIII.lIIIIllIllIIIIlIIlllIIlII(Minecraft:362)
	at lIIIllllllIIIllllIlIIlllI.lIIIlIlIIllllIllIIllIllIl(Minecraft:113)
	at Start.main(Minecraft:13)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at llIlllIIllIIIlIlIlIllIIII.llIIIlIlIllllIIllllIIIIll(Minecraft:598)
	at llIlllIIllIIIlIlIlIllIIII.IIlIIIIlllIlIIllIIIIlIlll(Minecraft:444)

-- Initialization --
Details:
Stacktrace:
	at llIlllIIllIIIlIlIlIllIIII.lIIIIllIllIIIIlIIlllIIlII(Minecraft:362)
	at lIIIllllllIIIllllIlIIlllI.lIIIlIlIIllllIllIIllIllIl(Minecraft:113)
	at Start.main(Minecraft:13)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	CPU: <unknown>
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 976745336 bytes (931 MB) / 1029177344 bytes (981 MB) up to 2132279296 bytes (2033 MB)
	JVM Flags: 5 total; -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmx2076M -Xms1024M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'cheatbreaker:?'
	Type: Client (map_client.txt)
	Resource Packs: 8X8 FPS BOOST PACK
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.8.9_HD_U_I7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 2

[2021-01-27 18:11:48.638] [info] ---- Minecraft Crash Report ----
1.8.9-?

// Who set us up the TNT?

Time: 1/27/21 7:11 PM
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at llIlllIIllIIIlIlIlIllIIII.llIIIlIlIllllIIllllIIIIll(Minecraft:598)
	at llIlllIIllIIIlIlIlIllIIII.IIlIIIIlllIlIIllIIIIlIlll(Minecraft:444)
	at llIlllIIllIIIlIlIlIllIIII.lIIIIllIllIIIIlIIlllIIlII(Minecraft:362)
	at lIIIllllllIIIllllIlIIlllI.lIIIlIlIIllllIllIIllIllIl(Minecraft:113)
	at Start.main(Minecraft:13)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at llIlllIIllIIIlIlIlIllIIII.llIIIlIlIllllIIllllIIIIll(Minecraft:598)
	at llIlllIIllIIIlIlIlIllIIII.IIlIIIIlllIlIIllIIIIlIlll(Minecraft:444)

-- Initialization --
Details:
Stacktrace:
	at llIlllIIllIIIlIlIlIllIIII.lIIIIllIllIIIIlIIlllIIlII(Minecraft:362)
	at lIIIllllllIIIllllIlIIlllI.lIIIlIlIIllllIllIIllIllIl(Minecraft:113)
	at Start.main(Minecraft:13)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	CPU: <unknown>
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 976745336 bytes (931 MB) / 1029177344 bytes (981 MB) up to 2132279296 bytes (2033 MB)
	JVM Flags: 5 total; -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmx2076M -Xms1024M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'cheatbreaker:?'
	Type: Client (map_client.txt)
	Resource Packs: 8X8 FPS BOOST PACK
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.8.9_HD_U_I7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 2

[2021-01-27 18:11:48.638] [info] ---- Minecraft Crash Report ----
1.8.9-?

// Who set us up the TNT?

Time: 1/27/21 7:11 PM
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at llIlllIIllIIIlIlIlIllIIII.llIIIlIlIllllIIllllIIIIll(Minecraft:598)
	at llIlllIIllIIIlIlIlIllIIII.IIlIIIIlllIlIIllIIIIlIlll(Minecraft:444)
	at llIlllIIllIIIlIlIlIllIIII.lIIIIllIllIIIIlIIlllIIlII(Minecraft:362)
	at lIIIllllllIIIllllIlIIlllI.lIIIlIlIIllllIllIIllIllIl(Minecraft:113)
	at Start.main(Minecraft:13)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at llIlllIIllIIIlIlIlIllIIII.llIIIlIlIllllIIllllIIIIll(Minecraft:598)
	at llIlllIIllIIIlIlIlIllIIII.IIlIIIIlllIlIIllIIIIlIlll(Minecraft:444)

-- Initialization --
Details:
Stacktrace:
	at llIlllIIllIIIlIlIlIllIIII.lIIIIllIllIIIIlIIlllIIlII(Minecraft:362)
	at lIIIllllllIIIllllIlIIlllI.lIIIlIlIIllllIllIIllIllIl(Minecraft:113)
	at Start.main(Minecraft:13)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	CPU: <unknown>
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 976745336 bytes (931 MB) / 1029177344 bytes (981 MB) up to 2132279296 bytes (2033 MB)
	JVM Flags: 5 total; -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmx2076M -Xms1024M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'cheatbreaker:?'
	Type: Client (map_client.txt)
	Resource Packs: 8X8 FPS BOOST PACK
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.8.9_HD_U_I7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 2

[2021-01-27 18:11:48.639] [info] ---- Minecraft Crash Report ----
1.8.9-?

// Who set us up the TNT?

Time: 1/27/21 7:11 PM
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at llIlllIIllIIIlIlIlIllIIII.llIIIlIlIllllIIllllIIIIll(Minecraft:598)

**Comment by ShonP40** [comment]
What's the model of the GPU you are using?

**Comment by zHeuzy** [comment]
Intel Graphics (I dont have Gpu)

**Comment by ShonP40** [comment]
Intel HD Graphics is a GPU (Graphics processing unit)
Do you know the exact model of it? (If not, can you send me the model of your CPU? (e.g. `i5-7600k`)

**Comment by zHeuzy** [comment]
Intel Graphics (I dont have Gpu)

**Comment by zHeuzy** [comment]
The Gpu we will say so and integrated into the processor

**Comment by ShonP40** [comment]
Whats the model of your CPU? (e.g. `i5-7600k`)

**Comment by zHeuzy** [comment]
And an Intel Pentium G630 (Yes and very bad, I'm just wanting to use CheatBreaker because they say it increases a lot of fps)

**Comment by ShonP40** [comment]
Looks like you have Intel HD Graphics 2000.
Unfortunately, Offline CheatBreaker doesn't support Intel HD Graphics 3000 and lower at the moment (You need at least IHD 4000 to play).

**Comment by zHeuzy** [comment]
Sad

**Comment by WTRM3L0N** [comment]
egg
